### ISSUE TITLE
hello,  badger updated?

### ISSUE THREAD

**Issue by dmanywhere** [zippoxer/bow#5]
../../../github.com/zippoxer/bow/db.go:308:9: cannot assign 1 values to 2 variables
../../../github.com/zippoxer/bow/db.go:308:22: not enough arguments in call to item.Value

**Comment by zippoxer** [comment]
Thanks for letting me know, I upgraded badger in the latest commit: 5ed1b7ff40c241257cc7e81b74bfab7d34070487.
