### ISSUE TITLE
Using int as key fails

### ISSUE THREAD

**Issue by vishr** [zippoxer/bow#7]
If your key is `int` or `uint` it fails in `Put()` with the following error `binary.Write failed: binary.Write: invalid type int` (https://play.golang.org/p/5U3qCrozRNJ) It is because encoding/binary is for fixed size data.

**Comment by zippoxer** [comment]
Fixed with commit 7c6a3dc6e9aef7b718382acdbadb86991ed77ab8. Thanks for reporting this 👍
